openapi: 3.0.0
info:
  description: Simple API to download a CV PDF for a person identified by first and
    last name.
  title: CV Download Service
  version: 1.0.0
servers:
- url: /
paths:
  /cv:
    get:
      description: Returns the CV of the person matching the given first and last
        name as a PDF file.
      operationId: cv_get
      parameters:
      - description: Person's first name
        explode: true
        in: query
        name: firstName
        required: true
        schema:
          type: string
        style: form
      - description: Person's last name
        explode: true
        in: query
        name: lastName
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/pdf:
              schema:
                format: binary
                type: string
          description: CV PDF file
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/_cv_get_404_response"
          description: CV not found
      summary: Download CV PDF
      tags:
      - cv
      x-openapi-router-controller: openapi_server.controllers.cv_controller
components:
  schemas:
    _cv_get_404_response:
      example:
        error: CV not found for John Doe
      properties:
        error:
          example: CV not found for John Doe
          title: error
          type: string
      title: _cv_get_404_response
      type: object
