# coding: utf-8

"""
    CV Download Service

    Simple API to download a CV PDF for a person identified by first and last name.

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.cv_api import router as CvApiRouter

app = FastAPI(
    title="CV Download Service",
    description="Simple API to download a CV PDF for a person identified by first and last name.",
    version="1.0.1",
)

app.include_router(CvApiRouter)
