openapi: 3.1.0
info:
  title: CV Download Service
  version: 1.0.1
  description: Simple API to download a CV PDF for a person identified by first and last name.

paths:
  /cv:
    post:
      tags:
        - cv
      summary: Download CV PDF
      description: Returns the CV of the person matching the given first and last name as a PDF file.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                  description: Person's first name
                  example: John
                lastName:
                  type: string
                  description: Person's last name
                  example: Doe
              required:
                - firstName
                - lastName
      responses:
        "200":
          description: CV PDF file
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        "404":
          description: CV not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "CV not found for John Doe"
