openapi: 3.0.0
info:
  title: CV Download Service
  version: 1.0.0
  description: Simple API to download a CV PDF for a person identified by first and last name.

paths:
  /cv:
    get:
      tags:
        - cv
      summary: Download CV PDF
      description: Returns the CV of the person matching the given first and last name as a PDF file.
      parameters:
        - name: firstName
          in: query
          description: Person's first name
          required: true
          schema:
            type: string
        - name: lastName
          in: query
          description: Person's last name
          required: true
          schema:
            type: string
      responses:
        "200":
          description: CV PDF file
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        "404":
          description: CV not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "CV not found for John Doe"
      security:
        - BearerAuth: []
  /health:
    get:
      tags:
        - health
      summary: Public health check
      responses:
        "200":
          description: Service is up
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
      security: []

