/* tslint:disable */
/* eslint-disable */
/**
 * CV Download Service
 * Simple API to download a CV PDF for a person identified by first and last name.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CvGet404Response,
} from '../models/index';
import {
    CvGet404ResponseFromJSON,
    CvGet404ResponseToJSON,
} from '../models/index';

export interface CvGetRequest {
    firstName: string;
    lastName: string;
}

/**
 * 
 */
export class CvApi extends runtime.BaseAPI {

    /**
     * Returns the CV of the person matching the given first and last name as a PDF file.
     * Download CV PDF
     */
    async cvGetRaw(requestParameters: CvGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['firstName'] == null) {
            throw new runtime.RequiredError(
                'firstName',
                'Required parameter "firstName" was null or undefined when calling cvGet().'
            );
        }

        if (requestParameters['lastName'] == null) {
            throw new runtime.RequiredError(
                'lastName',
                'Required parameter "lastName" was null or undefined when calling cvGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['firstName'] != null) {
            queryParameters['firstName'] = requestParameters['firstName'];
        }

        if (requestParameters['lastName'] != null) {
            queryParameters['lastName'] = requestParameters['lastName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/cv`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Returns the CV of the person matching the given first and last name as a PDF file.
     * Download CV PDF
     */
    async cvGet(requestParameters: CvGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.cvGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
