/* tslint:disable */
/* eslint-disable */
/**
 * CV Download Service
 * Simple API to download a CV PDF for a person identified by first and last name.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CvPost404Response,
  CvPostRequest,
} from '../models/index';
import {
    CvPost404ResponseFromJSON,
    CvPost404ResponseToJSON,
    CvPostRequestFromJSON,
    CvPostRequestToJSON,
} from '../models/index';

export interface CvPostOperationRequest {
    cvPostRequest: CvPostRequest;
}

/**
 * 
 */
export class CvApi extends runtime.BaseAPI {

    /**
     * Returns the CV of the person matching the given first and last name as a PDF file.
     * Download CV PDF
     */
    async cvPostRaw(requestParameters: CvPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['cvPostRequest'] == null) {
            throw new runtime.RequiredError(
                'cvPostRequest',
                'Required parameter "cvPostRequest" was null or undefined when calling cvPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/cv`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CvPostRequestToJSON(requestParameters['cvPostRequest']),
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Returns the CV of the person matching the given first and last name as a PDF file.
     * Download CV PDF
     */
    async cvPost(requestParameters: CvPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.cvPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
