/* tslint:disable */
/* eslint-disable */
/**
 * CV Download Service
 * Simple API to download a CV PDF for a person identified by first and last name.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CvGet404Response
 */
export interface CvGet404Response {
    /**
     * 
     * @type {string}
     * @memberof CvGet404Response
     */
    error?: string;
}

/**
 * Check if a given object implements the CvGet404Response interface.
 */
export function instanceOfCvGet404Response(value: object): value is CvGet404Response {
    return true;
}

export function CvGet404ResponseFromJSON(json: any): CvGet404Response {
    return CvGet404ResponseFromJSONTyped(json, false);
}

export function CvGet404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CvGet404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function CvGet404ResponseToJSON(json: any): CvGet404Response {
    return CvGet404ResponseToJSONTyped(json, false);
}

export function CvGet404ResponseToJSONTyped(value?: CvGet404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

