/* tslint:disable */
/* eslint-disable */
/**
 * CV Download Service
 * Simple API to download a CV PDF for a person identified by first and last name.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CvPostRequest
 */
export interface CvPostRequest {
    /**
     * Person's first name
     * @type {string}
     * @memberof CvPostRequest
     */
    firstName: string;
    /**
     * Person's last name
     * @type {string}
     * @memberof CvPostRequest
     */
    lastName: string;
}

/**
 * Check if a given object implements the CvPostRequest interface.
 */
export function instanceOfCvPostRequest(value: object): value is CvPostRequest {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function CvPostRequestFromJSON(json: any): CvPostRequest {
    return CvPostRequestFromJSONTyped(json, false);
}

export function CvPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CvPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
    };
}

export function CvPostRequestToJSON(json: any): CvPostRequest {
    return CvPostRequestToJSONTyped(json, false);
}

export function CvPostRequestToJSONTyped(value?: CvPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
    };
}

