/* tslint:disable */
/* eslint-disable */
/**
 * CV Download Service
 * Simple API to download a CV PDF for a person identified by first and last name.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CvPost404Response
 */
export interface CvPost404Response {
    /**
     * 
     * @type {string}
     * @memberof CvPost404Response
     */
    error?: string;
}

/**
 * Check if a given object implements the CvPost404Response interface.
 */
export function instanceOfCvPost404Response(value: object): value is CvPost404Response {
    return true;
}

export function CvPost404ResponseFromJSON(json: any): CvPost404Response {
    return CvPost404ResponseFromJSONTyped(json, false);
}

export function CvPost404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CvPost404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function CvPost404ResponseToJSON(json: any): CvPost404Response {
    return CvPost404ResponseToJSONTyped(json, false);
}

export function CvPost404ResponseToJSONTyped(value?: CvPost404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

